### ISSUE TITLE
API Token Use

### ISSUE THREAD

**Issue by r32rtb** [foospidy/logstash-input-signalsciences#2]
Provide the capability to utilize the x-api-user and x-api-token

**Comment by foospidy** [comment]
Thanks for requesting this. I should be able to add this very soon.

**Comment by foospidy** [comment]
Completed https://github.com/foospidy/logstash-input-signalsciences/commit/b2a29ec0555f0c024416cc703ccc00cc0cb53f95

Available in 1.0.0 release

**Comment by r32rtb** [comment]
I started working on this and just saw your update. :)  Mind if I make some further adjustments and get you a pull request?  I'd like to add the ability to use different info...  I need to pull the agent status...  I was going to make the get string configurable...

**Comment by foospidy** [comment]
That would be awesome, go for it!
